### ISSUE TITLE
creare un altro file php che apre un'altro csv con la lista dei musei

### ISSUE THREAD

**Issue by francescobianco** [ProgettoG55/OpenDataPartanna#4]
CAMPANILE DI SAN FRANCESCO
Unico elemento supersite del più antico complesso conventuale di Partanna, è... 
Comune: Partanna
Castello GrifeoCASTELLO GRIFEO
Il primo impianto del castello risale presumibilmente al XIV secolo, anche se la sua esistenza... 
Comune: Partanna
Chiesa del PurgatorioCHIESA DEL PURGATORIO
La facciata della chiesa del Purgatorio è testimonianza dello “scempio di... 
Comune: Partanna
Chiesa BadiellaCHIESA DELLA BADIELLA
Costruita nel XVIII secolo, conserva all’interno pregevoli affreschi. 
Comune: Partanna
Chiesa di San Francesco di PaolaCHIESA DI SAN FRANCESCO DI PAOLA
Edificata, per volere della famiglia Anelli, su una preesistente cappella dedicata a San... 
Comune: Partanna
Chiesa di San Nicol� da TolentinoCHIESA DI SAN NICOL� DA TOLENTINO
La chiesa, sebbene in precario stato di conservazione e priva di coperture, conserva tuttora... 
Comune: Partanna
Chiesa di San RoccoCHIESA DI SAN ROCCO
Sorta dopo la peste del 1576 in onore di San Rocco, protettore degli appestati, la chiesa... 
Comune: Partanna
Chiesa di Sant�Antonio AbateCHIESA DI SANT'ANTONIO ABATE
La piccola chiesa, sorse nel secolo XVI come cappella annessa al Monte di pietà.... 
Comune: Partanna
Chiesa e monastero di San BenedettoCHIESA E MONASTERO DI SAN BENEDETTO
Il complesso, voluto da don Domenico Grifeo che diede inizio i lavori nel 1660,  fu... 
Comune: Partanna
Madonna delle GrazieCHIESA MADONNA DELLE GRAZIE
Edificata nel 1500, presenta un campanile in tufo mai terminato e da poco restaurato. 
Comune: Partanna

**Comment by PieroSal92** [comment]
fatto
